### ISSUE TITLE
Can't select Redis DB

### ISSUE THREAD

**Issue by duylong** [statusengine/worker#2]
Hi,

We can't select the redis DB. Option missing with the redis library?

**Comment by nook24** [comment]
Hi @duylong,
Statusengine Worker always require an working Redis server, to store internal statistics (at the moment)
If you set `use_redis` to `1` in the config.yml, Statusengine will also save the current status information of host and service objects to the given Redis server.

However, the Statusengine Interface don't use the data out of Redis, due to the fact that there is no proper way of filter and sort data.

If you want to use the data inside of notification scripts for example, i would recommend you the query the information out of Redis, because the database has a bit of lag due to bulk sql statements.

You can also take a look at:
https://statusengine.org/worker/#in-memory

Hope this helps :)

**Comment by duylong** [comment]
I don't have a problem with Redis. I use Redis for multiples projects and I would select database in Redis (database in Redis is a number: 0, 1, ,2, 3...)

**Comment by nook24** [comment]
Ahh, ok now i got you. This should not a big deal, I will come back to you

**Comment by nook24** [comment]
Done in 3.1
