### ISSUE TITLE
Add Support for Elasticsearch 7

### ISSUE THREAD

**Issue by gangsterrapper22** [statusengine/worker#26]
I have installed Statusengine on CentOS 8 and I tried to exports the Metrics to Elasticsearch 7. 
I have read that only Elasticsearch 6 is supported but I tried it anyway, if it maybe will work, but this wasn't the case.
I get this Output when it tries to export to Elasticsearch 7 "{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Setting index.mapper.dynamic was removed after version 6.0.0"}],"type":"illegal_argument_exception","reason":"Setting index.mapper.dynamic was removed after version 6.0.0"},"status":400}"

Is there anything planned to add Elasticsearch 7 Support or maybe you can fix it?
Please let me know, if you need more information from me.

I use the Version 3.6.0

Thank you. 

Edit: It seems that the Data is get written to Elasticsearch, also with this Errror.

**Comment by nook24** [comment]
Have you installed the elasticsearch 7.0 driver for PHP?

```
apt-get install php-curl php-json php-mbstring
cd /opt/statusengine/worker
composer require elasticsearch/elasticsearch:~7.0 
```

Could you try to remove the following two lines and check if the issue is gone:
https://github.com/statusengine/worker/blob/01ab62614c03b1ad5793989c5284c0f4db6b6c7f/src/Backends/Elasticsearch/Template.php#L61
https://github.com/statusengine/worker/blob/01ab62614c03b1ad5793989c5284c0f4db6b6c7f/lib/Elasticsearch/template.json#L9

**Comment by gangsterrapper22** [comment]
I have installed the Elasticsearch 7.0 Driver for PHP and removed also the Lines "mapper.dynamic": false. Then I get this Error Message. I couldn't figure it out yet what has to be exaclty changed in the Template, that it is Elasticsearch 7 compatible.

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_default_ : {_source={enabled=true}, _all={enabled=false}}] [metric : {properties={hostname={type=keyword}, service_description={type=keyword}, @timestamp={type=date}, metric={type=keyword}, value={index=false, type=double}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {_source={enabled=true}, _all={enabled=false}}] [metric : {properties={hostname={type=keyword}, service_description={type=keyword}, @timestamp={type=date}, metric={type=keyword}, value={index=false, type=double}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_default_ : {_source={enabled=true}, _all={enabled=false}}] [metric : {properties={hostname={type=keyword}, service_description={type=keyword}, @timestamp={type=date}, metric={type=keyword}, value={index=false, type=double}}}]"}},"status":400}

**Comment by gangsterrapper22** [comment]
I will write a new commend, because this will get then confusing.
I did now now a complete reinstall of Centos 8, Naemon and Statusengine.
The only thing which I have now modified was removing '_type' => 'metric', and then it has worked.
https://github.com/statusengine/worker/blob/fb69e99f240b383db5c0bbaaba8599d86c5aba90/src/Backends/PerfdataBackends/ElasticsearchPerfdata.php#L96

This is the Output on Elasticsearch, when the Index was created: [statusengine-metric-2020.04] creating index, cause [auto(bulk api)], templates [statusengine-metric], shards [2]/[0], mappings [_doc]

If OK, I can create a Pull Request or you can fix it, but I don't know if this will break older Elasticsearch Installations.

**Comment by nook24** [comment]
Thanks for your investigation.
According to the docs the _type field got [deprecated in 6.0.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-type-field.html#mapping-type-field) and [removed in 7.0.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html)

>Initially, we spoke about an “index” being similar to a “database” in an SQL database, and a “type” being equivalent to a “table”.
>
>This was a bad analogy that led to incorrect assumptions...

I guess due to the fact that Statusengine always creates a own index to store performance date, it never it never makes use of the _type field.

> If OK, I can create a Pull Request or you can fix it, but I don't know if this will break older Elasticsearch Installations.

Yes of course. I'm not an expert when it comes to ES but I think it should not break older versions of elasticsearch.
I guess it could only break someone's queries?

**Comment by gangsterrapper22** [comment]
I will try to make a Pull Request, but I am not a expert to do this.
In the Statusengine UI I have seen, that the Performance Graph, display also no Graphs. I don't know, if this is also caused by this or if this another issue, or is there maybe a File which has the query in it for ES?

In the Statusengine-UI I have set:
display_perfdata: 1
perfdata_backend: elasticsearch
elasticsearch_pattern: monthly
elasticsearch_address: IP of ES Server
elasticsearch_port: 9200

Thanks.

**Comment by nook24** [comment]
Thanks for your feedback. If i find some time over the weekend i will try this with older ES versions and patch the code.

**Comment by duylong** [comment]
Hi,

Here is my template for working with ES7:
```
{
  "template": "statusengine-metric-*",
  "order": 0,
  "settings": {
    "index": {
      "number_of_shards": 1,
      "refresh_interval": "60s",
      "codec": "best_compression"
    }
  },
  "mappings": {
    "_source": {
      "enabled": "true"
    },
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "value": {
        "type": "double",
        "index": "false"
      },
      "hostname": {
        "type": "string",
        "index": "not_analyzed"
      },
      "service_description": {
        "type": "string",
        "index": "not_analyzed"
      },
      "metric": {
        "type": "string",
        "index": "not_analyzed"
      }
    }
  }
}
```

Files modified in order to adapt with new template:  
* worker/src/Backends/Elasticsearch/Template.php
* worker/lib/Elasticsearch/template.json

Others files:
* worker/etc/config.yml (remove enable_all)
* worker/src/Backends/PerfdataBackends/ElasticsearchPerfdata.php (remove "'_type' => 'metric'")
* interface/src/Loader/Elasticsearch/ServicePerfdataLoader.php (remove "'_type' => 'metric'")

**Comment by duylong** [comment]
I can still load my olds data (created in ES6) ;)

**Comment by nook24** [comment]
I added ES7 support in the [ES7 branch](https://github.com/statusengine/worker/tree/ES7).
Would be great if you guys could test this. :)

I will also patch the master branch of https://github.com/statusengine/interface

**Comment by duylong** [comment]
Everything seems correct to me :)

**Comment by jairoko** [comment]
hi, i am working in statusEngine  with ElasticSearch 7.10 and composer require elasticsearch/elasticsearch:~7.0.
I need to change the field @timestamp, because is long (unix time) and i need a date format (yyyy-MM-dd)

¿How can i change this type? I change template.json located in /opt/statusengine/worker/lib/Elasticsearch and the type is being long.

Furthermore, I do the steps indicated here whitout success. I need this format to do some graphics.

Attach the pictures with my configuration and problem to complete the description.

Thanks
![grafana](https://user-images.githubusercontent.com/78384876/106521029-ea83fa80-64dd-11eb-8a74-c687390cc7d2.JPG)
![index](https://user-images.githubusercontent.com/78384876/106521047-f1127200-64dd-11eb-8843-dce41299ef42.JPG)
![pattern](https://user-images.githubusercontent.com/78384876/106521060-f53e8f80-64dd-11eb-8faf-203d6d7719c9.JPG)
![statusengineUI](https://user-images.githubusercontent.com/78384876/106521085-fbcd0700-64dd-11eb-8678-c35b43977048.JPG)
![timestamp](https://user-images.githubusercontent.com/78384876/106521092-fff92480-64dd-11eb-948c-82313db01557.JPG)
[template.txt](https://github.com/statusengine/worker/files/5906906/template.txt)

**Comment by duylong** [comment]
"@timestamp" must be "type" => "date"

**Comment by nook24** [comment]
Sorry for my late response to this one. I will build the 3.7 Release over the weekend which also adds support for Elasticsearch 7. It's already available in the [ES7 branch](https://github.com/statusengine/worker/tree/ES7).
Tbh, i don't know why this isn't released already :(

**Comment by nook24** [comment]
Version 3.7 is released. Please see the changelog for update instructions: https://github.com/statusengine/worker/releases/tag/3.7.0
