### ISSUE TITLE
Additional information in the graphs

### ISSUE THREAD

**Issue by duylong** [statusengine/worker#3]
Is it easy to add the CRIT or WARN thresholds on the graphs? (with color lines on the graph for exemple). Similarly for ACK and DOWNTIME information? (with vertical lines for example for start and end periods)

or is it just to see a trend and is it better to use Grafana?

**Comment by nook24** [comment]
The graphs are just a basic implementation to see whats going on. They don't support fancy stuff like unit shifting (KB, MB, GB) or so.
All this can be done with Grafana, so I would recommend to build your Dashboards with Grafana.
Grafana also support thresholds lines...

Add Downtime or Acknowledgement information is more or less not possible, due to the fact that this information is (AFAIK) missing in the Nagios `NEBCALLBACK_SERVICE_CHECK_DATA` Event Broker Callback.
https://github.com/statusengine/module/blob/master/src/statusengine.c#L797-L892

To get information about Downtimes and Acknowledgements, the Worker needs to Query Redis or the Database for every single value, or the Interface needs to fetch the data out of the database, and merge it with the performance data records from the time series database.

Both options have some performance issues I guess. Redis would be the better one.
Also not all time series databases would allow to store extra field.

**Comment by duylong** [comment]
It is true that is not trivial with time series databases, but achievable with Graphite and Elasticsearch with the hierarchy of fields.

Redis is a good choice to think about. I think having some quick annotations on the graphs will help you understand quickly.

**Comment by nook24** [comment]
Quick question,
- do you want to display ACK and Downtime Ranges in the Statusengine UI Graph?
- or do you want to display this in Grafana?

**Comment by duylong** [comment]
Yes, I would like to display ACK and Downtime in the Statusengine graph. This avoids juggling between tools and identifying known behaviors.

**Comment by nook24** [comment]
Can you please move the issue to the [interface](https://github.com/statusengine/interface/) repository? I don't know but i guess if i copy it over, you will not get any notifications because you are no longer the author of the issue...

**Comment by duylong** [comment]
I can't move too. If you want, we can create a issue with a link to it.

**Comment by nook24** [comment]
This issue was moved to statusengine/interface#6
